version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1516112276
layout:
  /top/:
    -
      - system-messages-8181
    -
      - 'position-1813 33'
      - 'position-6382 34'
      - 'position-4006 33'
  /header/:
    -
      - 'logo-3253 25'
      - 'horizontalmenu-5961 75'
    -
      - 'position-4360 33'
      - 'position-4603 34'
      - 'position-1870 33'
  /navigation/:
    -
      - menu-9462
  /slideshow/:
    -
      - position-2315
  /showcase/:
    -
      - 'position-8946 33'
      - 'position-2143 34'
      - 'position-3683 33'
  /feature/:
    -
      - 'position-5626 33'
      - 'position-1917 34'
      - 'position-6379 33'
  /main/:
    -
      - 'position-3118 33'
      - 'position-8147 34'
      - 'position-9507 33'
  /container-4685/:
    -
      -
        'sidebar 20':
          -
            - position-8349
      -
        'mainbar 60':
          -
            - system-content-7296
      -
        'aside 20':
          -
            - position-5179
  /extension/:
    -
      - 'position-6339 33'
      - 'position-2625 34'
      - 'position-5523 33'
  /bottom/:
    -
      - 'position-1903 33'
      - 'position-1485 34'
      - 'position-8876 33'
  /footer/:
    -
      - 'position-5596 33'
      - 'position-6733 34'
      - 'position-7703 33'
  /copyright/:
    -
      - 'logo-2450 33'
      - 'custom-8337 67'
    -
      - 'copyright-5895 33'
      - 'horizontalmenu-4825 57'
      - 'totop-5624 10'
  offcanvas:
    -
      - mobile-menu-6590
structure:
  top:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-4685:
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
content:
  system-messages-8181:
    block:
      variations: 'nomarginall nopaddingall'
  position-1813:
    title: 'Top A'
    attributes:
      key: top-a
  position-6382:
    title: 'Top B'
    attributes:
      key: top-b
  position-4006:
    title: 'Top C'
    attributes:
      key: top-c
  logo-3253:
    block:
      class: g-logo-block
  horizontalmenu-5961:
    title: 'Top Menu'
    attributes:
      target: _blank
      text:
        -
          text: Features
          link: 'http://docs.gantry.org/gantry5/basics/key-features'
          name: Features
        -
          text: 'Gantry 5'
          link: 'http://www.gantry.org/'
          name: 'Gantry 5'
        -
          text: Particles
          link: 'http://docs.gantry.org/gantry5/particles'
          name: Particles
        -
          text: Download
          link: 'https://www.rockettheme.com/joomla/templates/ambrosia'
          name: Download
        -
          text: Support
          link: 'https://www.rockettheme.com/forum/joomla-template-ambrosia'
          name: Support
    block:
      class: g-menu-block
  position-4360:
    title: 'Header A'
    attributes:
      key: header-a
  position-4603:
    title: 'Header B'
    attributes:
      key: header-b
  position-1870:
    title: 'Header C'
    attributes:
      key: header-c
  menu-9462:
    block:
      class: g-ambrosia-menu
  position-2315:
    title: Slideshow
    attributes:
      key: slideshow
    block:
      class: flush
  position-8946:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-2143:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-3683:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-5626:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-1917:
    title: 'Feature B'
    attributes:
      key: feature-b
  position-6379:
    title: 'Feature C'
    attributes:
      key: feature-c
  position-3118:
    title: 'Main A'
    attributes:
      key: main-a
  position-8147:
    title: 'Main B'
    attributes:
      key: main-b
  position-9507:
    title: 'Main C'
    attributes:
      key: main-c
  position-8349:
    title: Sidebar
    attributes:
      key: sidebar
  position-5179:
    title: Aside
    attributes:
      key: aside
  position-6339:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-2625:
    title: 'Extension B'
    attributes:
      key: extension-b
  position-5523:
    title: 'Extension C'
    attributes:
      key: extension-c
  position-1903:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-1485:
    title: 'Bottom B'
    attributes:
      key: bottom-b
  position-8876:
    title: 'Bottom C'
    attributes:
      key: bottom-c
  position-5596:
    title: 'Footer A'
    attributes:
      key: footer-a
  position-6733:
    title: 'Footer B'
    attributes:
      key: footer-b
  position-7703:
    title: 'Footer C'
    attributes:
      key: footer-c
  logo-2450:
    attributes:
      image: ''
  custom-8337:
    title: 'Demo Information'
    attributes:
      html: "<div class=\"g-tag\"><a href=\"#\">Demo Information</a></div>\n\n<p>All demo content is for sample purposes only, intended to represent a live site. All content images are licensed from their respective sources for exclusive use on this demo only.</p>"
    block:
      class: bordered-bottom
  copyright-5895:
    attributes:
      date:
        start: '2007'
      owner: 'RocketTheme, LLC'
    block:
      class: g-copyright
  horizontalmenu-4825:
    title: 'Bottom Menu'
    attributes:
      target: _blank
      text:
        -
          text: Features
          link: 'http://docs.gantry.org/gantry5/basics/key-features'
          name: Features
        -
          text: 'Gantry 5'
          link: 'http://www.gantry.org/'
          name: 'Gantry 5'
        -
          text: Particles
          link: 'http://docs.gantry.org/gantry5/particles'
          name: Particles
        -
          text: Download
          link: 'https://www.rockettheme.com/joomla/templates/ambrosia'
          name: Download
        -
          text: Support
          link: 'https://www.rockettheme.com/forum/joomla-template-ambrosia'
          name: Support
  totop-5624:
    title: 'To Top'
    attributes:
      content: '<i class="fa fa-fw fa-2x fa-arrow-circle-o-up"></i>'
  mobile-menu-6590:
    title: 'Mobile Menu'
