name: Base Styles - Style podstawowe
description: Style podstawowe dla motywu Hydrogen
type: core

form:
  fields:
  
    _info_common:
      type: separator.note
      class: alert alert-info
      content: '<b>Base Styles</b> Parametry dla stylu podstawowego. Więcej o stylach tutaj <a href="http://docs.gantry.org/gantry5/configure/styles" target="_blank" title="Przykłady zastosowania">(Styles)</a> i tutaj <a href="https://material.io/design/color/#" target="_blank" title="Przykłady zastosowania"><i class="fa fa-external-link"></i> (material.io)</a> O kolorach akcentujących tutaj <a href="https://www.material-theme.com/docs/configuration/accents/" target="_blank" title="Przykłady zastosowania"><i class="fa fa-external-link"></i> (Accent Colors)</a> <br><b>Jeśli chcesz, aby ustawienia konturu powróciły do ​​wartości domyślnych, usuń zaznaczenie pola wyboru i zapisz styl.</b>'
  
      background:
      type: input.colorpicker
      label: Tło podstawowe
      default: "#ffffff"
    text-color:
      type: input.colorpicker
      label: Podstawowy kolor tekstu
      default: "#424753"
