name: Style podstawowe
description: Base styles for the Hydrogen theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Podstawowy kolor tła
      default: "#ffffff"
    text-color:
      type: input.colorpicker
      label: Podstawowy kolor tekstu
      default: "#666666"
    body-font:
      type: input.fonts
      label: Czcionka strony
      default: 'roboto, sans-serif'
    heading-font:
      type: input.fonts
      label: Czcionka nagłówka
      default: 'roboto, sans-serif'
