name: _offline
timestamp: 1565080684
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1565080684
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-6550: Logo
  spacer:
    spacer-3914: Spacer
    spacer-9669: Spacer
  messages:
    system-messages-3686: 'System Messages'
  content:
    system-content-5426: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-9220: Copyright
  branding:
    branding-4864: Branding
inherit: {  }
