version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1565080684
layout:
  /header/:
    -
      - 'logo-6550 30'
      - 'spacer-3914 70'
  /main/:
    -
      - system-messages-3686
    -
      - system-content-5426
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9220 40'
      - 'spacer-9669 30'
      - 'branding-4864 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
