name: Style podstawowe
description: Base styles for the Helium theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Podstawowy kolor tła
      default: "#ffffff"
    text-color:
      type: input.colorpicker
      label: Podstawowy kolor tekstu
      default: "#424753"
