name: _error
timestamp: 1672995192
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1672995192
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4382: Logo
  spacer:
    spacer-9621: Spacer
    spacer-8211: Spacer
  menu:
    menu-4811: Menu
  content:
    system-content-3517: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-4498: Copyright
  branding:
    branding-2455: Branding
  mobile-menu:
    mobile-menu-1615: Mobile-menu
inherit: {  }
