name: _error
timestamp: 1565080684
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1565080684
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5168: Logo
  spacer:
    spacer-5050: Spacer
    spacer-3030: Spacer
  menu:
    menu-7132: Menu
  content:
    system-content-9363: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-4847: Copyright
  branding:
    branding-5248: Branding
  mobile-menu:
    mobile-menu-7626: Mobile-menu
inherit: {  }
