version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1572889809
layout:
  /navigation/:
    -
      - 'logo-5679 15'
      - 'social-8430 20'
      - 'menu-2875 50'
      - 'search-9026 15'
  /showcase/:
    -
      - 'position-position-2621 25'
      - 'position-position-4680 25'
      - 'position-position-4839 25'
      - 'position-position-1217 25'
  /breadcrumb/:
    -
      - position-position-2216
  /utility/:
    -
      - 'position-position-3724 25'
      - 'position-position-2653 25'
      - 'position-position-3401 25'
      - 'position-position-1491 25'
  /feature/:
    -
      - 'position-position-4543 25'
      - 'position-position-5434 25'
      - 'position-position-5489 25'
      - 'position-position-8898 25'
  /maintop/:
    -
      - 'position-position-2723 25'
      - 'position-position-7137 25'
      - 'position-position-3102 25'
      - 'position-position-1823 25'
  /container-main/:
    -
      -
        'main 67':
          -
            - system-content-6489
      -
        'sidebar 33':
          -
            - position-position-7684
  /mainbottom/:
    -
      - 'position-position-7827 25'
      - 'position-position-4155 25'
      - 'position-position-2697 25'
      - 'position-position-1720 25'
  /extension/:
    -
      - 'position-position-3769 25'
      - 'position-position-2063 25'
      - 'position-position-6577 25'
      - 'position-position-1027 25'
  /bottom/:
    -
      - 'position-position-2796 25'
      - 'position-position-7267 25'
      - 'position-position-5690 25'
      - 'position-position-7655 25'
  /footer/:
    -
      - 'position-position-4077 25'
      - 'position-position-4480 25'
      - 'position-position-9100 25'
      - 'position-position-6570 25'
  /copyright/:
    -
      - 'branding-4486 30'
      - 'custom-2657 45'
      - 'totop-3411 25'
  offcanvas:
    -
      - mobile-menu-4892
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  breadcrumb:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  maintop:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  main:
    attributes:
      class: ''
      variations: ''
    block:
      class: main
  sidebar:
    type: section
    attributes:
      class: ''
      variations: ''
    block:
      class: sidebar
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  footer:
    attributes:
      boxed: ''
      class: ''
      variations: ''
  copyright:
    type: section
    attributes:
      boxed: ''
      class: center
      variations: ''
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '0'
      css3animation: '1'
content:
  logo-5679:
    attributes:
      image: 'gantry-media://logo/logo.png'
      link: '1'
      class: g-logo
  social-8430:
    block:
      class: social
  menu-2875:
    block:
      class: g-audacity-menu
      variations: 'center nomarginall nopaddingall'
  search-9026:
    attributes:
      title: ''
      placeholder: Search...
    block:
      class: 'search hidden-phone'
      variations: 'nomarginbottom nopaddingbottom nopaddingtop'
  position-position-2621:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-4680:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-position-4839:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-position-1217:
    title: 'Showcase D'
    attributes:
      key: showcase-d
  position-position-2216:
    title: Breadcrumb
    attributes:
      key: breadcrumb
  position-position-3724:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-2653:
    title: 'Utility B'
    attributes:
      key: utility-b
  position-position-3401:
    title: 'Utility C'
    attributes:
      key: utility-c
  position-position-1491:
    title: 'Utility D'
    attributes:
      key: utility-d
  position-position-4543:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-5434:
    title: 'Feature B'
    attributes:
      key: feature-b
  position-position-5489:
    title: 'Feature C'
    attributes:
      key: feature-c
  position-position-8898:
    title: 'Feature D'
    attributes:
      key: feature-d
  position-position-2723:
    title: 'Maintop A'
    attributes:
      key: maintop-a
  position-position-7137:
    title: 'MainTop B'
    attributes:
      key: maintop-b
  position-position-3102:
    title: 'MainTop C'
    attributes:
      key: maintop-c
  position-position-1823:
    title: 'MainTop D'
    attributes:
      key: maintop-d
  position-position-7684:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
    block:
      variations: 'nomarginall nopaddingall'
  position-position-7827:
    title: 'MainBottom A'
    attributes:
      key: mainbottom-a
  position-position-4155:
    title: 'MainBottom B'
    attributes:
      key: mainbottom-b
  position-position-2697:
    title: 'MainBottom C'
    attributes:
      key: mainbottom-c
  position-position-1720:
    title: 'MainBottom D'
    attributes:
      key: mainbottom-d
  position-position-3769:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-2063:
    title: 'Extension B'
    attributes:
      key: extension-b
  position-position-6577:
    title: 'Extension C'
    attributes:
      key: extension-c
  position-position-1027:
    title: 'Extension D'
    attributes:
      key: extension-d
  position-position-2796:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-7267:
    title: 'Bottom B'
    attributes:
      key: bottom-b
  position-position-5690:
    title: 'Bottom C'
    attributes:
      key: bottom-c
  position-position-7655:
    title: 'Bottom D'
    attributes:
      key: bottom-d
  position-position-4077:
    title: 'Footer A'
    attributes:
      key: footer-a
  position-position-4480:
    title: 'Footer B'
    attributes:
      key: footer-b
  position-position-9100:
    title: 'Footer C'
    attributes:
      key: footer-c
  position-position-6570:
    title: 'Footer D'
    attributes:
      key: footer-d
  branding-4486:
    attributes:
      content: '<a href="http://www.rockettheme.com/" title="RocketTheme" class="rt-powered-by"></a>'
      css:
        class: ''
    block:
      class: branding
  custom-2657:
    title: 'Custom HTML'
    attributes:
      title: ''
      titletag: ''
      html: 'Developed by <a href="http://www.rockettheme.com">RocketTheme</a>. Photos by <a href="https://tookapic.com/">tookapic</a>.'
      twig: '0'
      filter: '0'
    block:
      class: copyright
  totop-3411:
    title: 'To Top'
    block:
      class: mobile-center
  mobile-menu-4892:
    title: 'Mobile Menu'
