name: _body_only
timestamp: 1565080684
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1565080684
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-4884: 'System Messages'
  content:
    system-content-7521: 'Page Content'
inherit: {  }
