version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1672995192
layout:
  /header/:
    -
      - 'logo-6230 30'
      - 'spacer-7086 70'
  /main/:
    -
      - system-messages-9859
    -
      - system-content-4579
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3788 40'
      - 'spacer-6144 30'
      - 'branding-7912 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
