name: _body_only
timestamp: 1672995192
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1672995192
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-4316: 'System Messages'
  content:
    system-content-8777: 'Page Content'
inherit: {  }
